<?php

namespace Database\Seeders;

use App\Models\Ability;
use App\Models\Animal;
use App\Models\AnimalClass;
use App\Models\ConservationStatus;
use App\Models\Continent;
use App\Models\Diet;
use App\Models\Habitat;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;

class AnimalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $animalClasses = AnimalClass::all();
        $diets = Diet::all();
        $conservationStatuses = ConservationStatus::all();
        $habitats = Habitat::all();
        $continents = Continent::all();
        $abilities = Ability::all();

        $animals = $animals = [
            [
                'name' => 'Leone',
                'scientific_name' => 'Panthera leo',
                'description' => 'Grande felino sociale, simbolo della savana africana e famoso per il ruggito potente.',
                'weight_kg' => 190,
                'length_cm' => 250,
                'height_cm' => 120,
                'lifespan_years' => 14,
                'animal_class' => 'mammiferi',
                'diet' => 'carnivoro',
                'conservation_status' => 'vulnerabile',
                'habitats' => ['prateria-savana'],
                'continents' => ['africa', 'asia'],
                'abilities' => ['forza-eccezionale', 'comunicazione-sonora', 'velocita'],
            ],
            [
                'name' => 'Panda gigante',
                'scientific_name' => 'Ailuropoda melanoleuca',
                'description' => 'Mammifero asiatico riconoscibile dal mantello bianco e nero, si nutre soprattutto di bambù.',
                'weight_kg' => 100,
                'length_cm' => 170,
                'height_cm' => 90,
                'lifespan_years' => 20,
                'animal_class' => 'mammiferi',
                'diet' => 'erbivoro',
                'conservation_status' => 'vulnerabile',
                'habitats' => ['foresta-bosco', 'montagna'],
                'continents' => ['asia'],
                'abilities' => ['arrampicata', 'forza-eccezionale'],
            ],
            [
                'name' => 'Aquila reale',
                'scientific_name' => 'Aquila chrysaetos',
                'description' => 'Grande rapace di montagna, dotato di vista acutissima e volo potente.',
                'weight_kg' => 6,
                'length_cm' => 90,
                'height_cm' => 85,
                'lifespan_years' => 30,
                'animal_class' => 'uccelli',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['montagna', 'prateria-savana'],
                'continents' => ['europa', 'asia', 'america-del-nord'],
                'abilities' => ['volo', 'velocita'],
            ],
            [
                'name' => 'Pappagallo ara',
                'scientific_name' => 'Ara macao',
                'description' => 'Pappagallo tropicale dai colori vivaci, intelligente e molto comunicativo.',
                'weight_kg' => 1,
                'length_cm' => 85,
                'height_cm' => 40,
                'lifespan_years' => 50,
                'animal_class' => 'uccelli',
                'diet' => 'frugivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco'],
                'continents' => ['america-del-sed'],
                'abilities' => ['volo', 'comunicazione-sonora', 'arrampicata'],
            ],
            [
                'name' => 'Delfino tursiope',
                'scientific_name' => 'Tursiops truncatus',
                'description' => 'Cetaceo intelligente e sociale, famoso per i salti, i fischi e l’ecolocalizzazione.',
                'weight_kg' => 300,
                'length_cm' => 350,
                'height_cm' => null,
                'lifespan_years' => 40,
                'animal_class' => 'mammiferi',
                'diet' => 'piscivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['mare-oceano'],
                'continents' => ['africa', 'europa', 'asia', 'america-del-nord', 'america-del-sed', 'oceania'],
                'abilities' => ['ecolocalizzazione', 'nuoto-rapido', 'comunicazione-sonora'],
            ],

            [
                'name' => 'Lucciola',
                'scientific_name' => 'Lampyris noctiluca',
                'description' => 'Insetto noto per la capacità di produrre luce naturale durante la notte.',
                'weight_kg' => 0.001,
                'length_cm' => 2,
                'height_cm' => 1,
                'lifespan_years' => 1,
                'animal_class' => 'insetti',
                'diet' => 'insettivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco', 'palude'],
                'continents' => ['europa', 'asia'],
                'abilities' => ['bioluminescenza', 'volo'],
            ],
            [
                'name' => 'Ape mellifera',
                'scientific_name' => 'Apis mellifera',
                'description' => 'Insetto impollinatore fondamentale per molti ecosistemi, vive in colonie organizzate.',
                'weight_kg' => 0.0001,
                'length_cm' => 1,
                'height_cm' => 1,
                'lifespan_years' => 1,
                'animal_class' => 'insetti',
                'diet' => 'nettarivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco', 'prateria-savana'],
                'continents' => ['africa', 'europa', 'asia', 'america-del-nord', 'america-del-sed', 'oceania'],
                'abilities' => ['volo', 'comunicazione-sonora'],
            ],
            [
                'name' => 'Pesce palla',
                'scientific_name' => 'Tetraodontidae',
                'description' => 'Pesce capace di gonfiarsi per difesa; alcune specie producono potenti tossine.',
                'weight_kg' => 2,
                'length_cm' => 40,
                'height_cm' => null,
                'lifespan_years' => 10,
                'animal_class' => 'pesci',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['mare-oceano'],
                'continents' => ['africa', 'asia', 'oceania'],
                'abilities' => ['veleno', 'corazza'],
            ],
            [
                'name' => 'Narvalo',
                'scientific_name' => 'Monodon monoceros',
                'description' => 'Cetaceo artico famoso per la lunga zanna a spirale dei maschi.',
                'weight_kg' => 1200,
                'length_cm' => 500,
                'height_cm' => null,
                'lifespan_years' => 50,
                'animal_class' => 'mammiferi',
                'diet' => 'piscivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['mare-oceano', 'artico-polare'],
                'continents' => ['america-del-nord', 'europa'],
                'abilities' => ['ecolocalizzazione', 'nuoto-rapido', 'termoregolazione-estrema'],
            ],
            [
                'name' => 'Rana arboricola verde',
                'scientific_name' => 'Hyla cinerea',
                'description' => 'Piccola rana verde capace di arrampicarsi tra rami e foglie vicino all’acqua.',
                'weight_kg' => 0.01,
                'length_cm' => 6,
                'height_cm' => 3,
                'lifespan_years' => 5,
                'animal_class' => 'anfibi',
                'diet' => 'insettivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco', 'palude', 'fiume-lago'],
                'continents' => ['america-del-nord'],
                'abilities' => ['arrampicata', 'salto'],
            ],

            [
                'name' => 'Scarabeo rinoceronte',
                'scientific_name' => 'Oryctes nasicornis',
                'description' => 'Insetto robusto con un caratteristico corno, noto per la grande forza rispetto alle dimensioni.',
                'weight_kg' => 0.02,
                'length_cm' => 6,
                'height_cm' => 3,
                'lifespan_years' => 3,
                'animal_class' => 'insetti',
                'diet' => 'erbivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco'],
                'continents' => ['europa', 'asia'],
                'abilities' => ['forza-eccezionale', 'corazza', 'volo'],
            ],
            [
                'name' => 'Cobra reale',
                'scientific_name' => 'Ophiophagus hannah',
                'description' => 'Grande serpente velenoso asiatico, capace di sollevare la parte anteriore del corpo.',
                'weight_kg' => 6,
                'length_cm' => 400,
                'height_cm' => null,
                'lifespan_years' => 20,
                'animal_class' => 'rettili',
                'diet' => 'carnivoro',
                'conservation_status' => 'vulnerabile',
                'habitats' => ['foresta-bosco', 'palude'],
                'continents' => ['asia'],
                'abilities' => ['veleno', 'mimetismo'],
            ],
            [
                'name' => 'Tarantola golia',
                'scientific_name' => 'Theraphosa blondi',
                'description' => 'Uno dei ragni più grandi al mondo, vive nelle foreste tropicali del Sud America.',
                'weight_kg' => 0.17,
                'length_cm' => 30,
                'height_cm' => null,
                'lifespan_years' => 20,
                'animal_class' => 'aracnidi',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco'],
                'continents' => ['america-del-sed'],
                'abilities' => ['veleno', 'produzione-seta', 'arrampicata'],
            ],
            [
                'name' => 'Anguilla elettrica',
                'scientific_name' => 'Electrophorus electricus',
                'description' => 'Pesce d’acqua dolce capace di generare scariche elettriche per caccia e difesa.',
                'weight_kg' => 20,
                'length_cm' => 200,
                'height_cm' => null,
                'lifespan_years' => 15,
                'animal_class' => 'pesci',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['fiume-lago'],
                'continents' => ['america-del-sed'],
                'abilities' => ['elettrocezione', 'nuoto-rapido'],
            ],
            [
                'name' => 'Armadillo',
                'scientific_name' => 'Dasypodidae',
                'description' => 'Mammifero americano protetto da placche ossee che formano una corazza naturale.',
                'weight_kg' => 5,
                'length_cm' => 75,
                'height_cm' => 25,
                'lifespan_years' => 15,
                'animal_class' => 'mammiferi',
                'diet' => 'insettivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['prateria-savana', 'foresta-bosco'],
                'continents' => ['america-del-nord', 'america-del-sed'],
                'abilities' => ['corazza', 'arrampicata'],
            ],

            [
                'name' => 'Polpo comune',
                'scientific_name' => 'Octopus vulgaris',
                'description' => 'Mollusco marino molto intelligente, capace di cambiare colore e infilarsi in spazi stretti.',
                'weight_kg' => 8,
                'length_cm' => 100,
                'height_cm' => null,
                'lifespan_years' => 2,
                'animal_class' => 'molluschi',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['mare-oceano'],
                'continents' => ['africa', 'europa', 'asia'],
                'abilities' => ['mimetismo', 'rigenerazione'],
            ],
            [
                'name' => 'Squalo bianco',
                'scientific_name' => 'Carcharodon carcharias',
                'description' => 'Grande predatore marino, potente e veloce, al vertice della catena alimentare oceanica.',
                'weight_kg' => 1100,
                'length_cm' => 600,
                'height_cm' => null,
                'lifespan_years' => 70,
                'animal_class' => 'pesci',
                'diet' => 'carnivoro',
                'conservation_status' => 'vulnerabile',
                'habitats' => ['mare-oceano'],
                'continents' => ['africa', 'europa', 'asia', 'america-del-nord', 'america-del-sed', 'oceania'],
                'abilities' => ['elettrocezione', 'nuoto-rapido', 'forza-eccezionale'],
            ],
            [
                'name' => 'Orso bruno',
                'scientific_name' => 'Ursus arctos',
                'description' => 'Grande mammifero onnivoro delle foreste e montagne dell’emisfero nord.',
                'weight_kg' => 300,
                'length_cm' => 250,
                'height_cm' => 150,
                'lifespan_years' => 25,
                'animal_class' => 'mammiferi',
                'diet' => 'onnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco', 'montagna'],
                'continents' => ['europa', 'asia', 'america-del-nord'],
                'abilities' => ['forza-eccezionale', 'arrampicata'],
            ],
            [
                'name' => 'Gambero mantide',
                'scientific_name' => 'Stomatopoda',
                'description' => 'Crostaceo marino dai colori vivaci, famoso per colpi rapidissimi e potenti.',
                'weight_kg' => 0.09,
                'length_cm' => 30,
                'height_cm' => null,
                'lifespan_years' => 6,
                'animal_class' => 'crostacei',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['mare-oceano'],
                'continents' => ['asia', 'oceania'],
                'abilities' => ['velocita', 'forza-eccezionale', 'corazza'],
            ],
            [
                'name' => 'Nautilus',
                'scientific_name' => 'Nautilus pompilius',
                'description' => 'Antico mollusco marino con conchiglia a spirale, considerato un fossile vivente.',
                'weight_kg' => 1,
                'length_cm' => 25,
                'height_cm' => null,
                'lifespan_years' => 20,
                'animal_class' => 'molluschi',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['mare-oceano'],
                'continents' => ['asia', 'oceania'],
                'abilities' => ['corazza', 'nuoto-rapido'],
            ],

            [
                'name' => 'Tigre del Bengala',
                'scientific_name' => 'Panthera tigris tigris',
                'description' => 'Grande felino asiatico dal mantello striato, predatore solitario e potente.',
                'weight_kg' => 220,
                'length_cm' => 310,
                'height_cm' => 110,
                'lifespan_years' => 15,
                'animal_class' => 'mammiferi',
                'diet' => 'carnivoro',
                'conservation_status' => 'in-pericolo',
                'habitats' => ['foresta-bosco', 'palude'],
                'continents' => ['asia'],
                'abilities' => ['mimetismo', 'forza-eccezionale', 'nuoto-rapido'],
            ],
            [
                'name' => 'Falco pellegrino',
                'scientific_name' => 'Falco peregrinus',
                'description' => 'Rapace velocissimo, celebre per le picchiate ad altissima velocità.',
                'weight_kg' => 1,
                'length_cm' => 50,
                'height_cm' => 45,
                'lifespan_years' => 15,
                'animal_class' => 'uccelli',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['montagna', 'prateria-savana'],
                'continents' => ['africa', 'europa', 'asia', 'america-del-nord', 'america-del-sed', 'oceania'],
                'abilities' => ['volo', 'velocita'],
            ],
            [
                'name' => 'Squalo martello',
                'scientific_name' => 'Sphyrnidae',
                'description' => 'Squalo riconoscibile dalla testa allargata, utile per orientarsi e trovare prede.',
                'weight_kg' => 230,
                'length_cm' => 400,
                'height_cm' => null,
                'lifespan_years' => 30,
                'animal_class' => 'pesci',
                'diet' => 'carnivoro',
                'conservation_status' => 'in-pericolo',
                'habitats' => ['mare-oceano'],
                'continents' => ['africa', 'asia', 'america-del-nord', 'america-del-sed', 'oceania'],
                'abilities' => ['elettrocezione', 'nuoto-rapido'],
            ],
            [
                'name' => 'Drago di Komodo',
                'scientific_name' => 'Varanus komodoensis',
                'description' => 'Grande varano indonesiano, potente predatore terrestre.',
                'weight_kg' => 80,
                'length_cm' => 300,
                'height_cm' => 60,
                'lifespan_years' => 30,
                'animal_class' => 'rettili',
                'diet' => 'carnivoro',
                'conservation_status' => 'in-pericolo',
                'habitats' => ['foresta-bosco', 'prateria-savana'],
                'continents' => ['asia'],
                'abilities' => ['veleno', 'forza-eccezionale'],
            ],
            [
                'name' => 'Farfalla monarca',
                'scientific_name' => 'Danaus plexippus',
                'description' => 'Insetto migratore noto per le lunghe migrazioni e le ali arancioni e nere.',
                'weight_kg' => 0.001,
                'length_cm' => 10,
                'height_cm' => 1,
                'lifespan_years' => 1,
                'animal_class' => 'insetti',
                'diet' => 'nettarivoro',
                'conservation_status' => 'vulnerabile',
                'habitats' => ['prateria-savana', 'foresta-bosco'],
                'continents' => ['america-del-nord'],
                'abilities' => ['volo', 'mimetismo'],
            ],

            [
                'name' => 'Elefante africano',
                'scientific_name' => 'Loxodonta africana',
                'description' => 'Il più grande animale terrestre vivente, dotato di proboscide, zanne e memoria notevole.',
                'weight_kg' => 6000,
                'length_cm' => 700,
                'height_cm' => 330,
                'lifespan_years' => 70,
                'animal_class' => 'mammiferi',
                'diet' => 'erbivoro',
                'conservation_status' => 'in-pericolo',
                'habitats' => ['prateria-savana', 'foresta-bosco'],
                'continents' => ['africa'],
                'abilities' => ['forza-eccezionale', 'comunicazione-sonora'],
            ],
            [
                'name' => 'Gufo reale',
                'scientific_name' => 'Bubo bubo',
                'description' => 'Grande rapace notturno, riconoscibile dagli occhi frontali e dal volo silenzioso.',
                'weight_kg' => 3,
                'length_cm' => 75,
                'height_cm' => 70,
                'lifespan_years' => 20,
                'animal_class' => 'uccelli',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco', 'montagna'],
                'continents' => ['europa', 'asia'],
                'abilities' => ['volo', 'visione-notturna'],
            ],
            [
                'name' => 'Manta gigante',
                'scientific_name' => 'Mobula birostris',
                'description' => 'Grande pesce cartilagineo che nuota elegantemente filtrando piccoli organismi marini.',
                'weight_kg' => 1600,
                'length_cm' => 700,
                'height_cm' => null,
                'lifespan_years' => 40,
                'animal_class' => 'pesci',
                'diet' => 'carnivoro',
                'conservation_status' => 'in-pericolo',
                'habitats' => ['mare-oceano'],
                'continents' => ['africa', 'asia', 'america-del-nord', 'america-del-sed', 'oceania'],
                'abilities' => ['nuoto-rapido', 'elettrocezione'],
            ],
            [
                'name' => 'Camaleonte pantera',
                'scientific_name' => 'Furcifer pardalis',
                'description' => 'Rettile arboricolo dai colori vivaci, capace di mimetizzarsi e muovere gli occhi indipendentemente.',
                'weight_kg' => 0.18,
                'length_cm' => 50,
                'height_cm' => 10,
                'lifespan_years' => 7,
                'animal_class' => 'rettili',
                'diet' => 'insettivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco'],
                'continents' => ['africa'],
                'abilities' => ['mimetismo', 'arrampicata'],
            ],
            [
                'name' => 'Mantide religiosa',
                'scientific_name' => 'Mantis religiosa',
                'description' => 'Insetto predatore dalle zampe anteriori raptatorie, capace di restare immobile in agguato.',
                'weight_kg' => 0.005,
                'length_cm' => 8,
                'height_cm' => 4,
                'lifespan_years' => 1,
                'animal_class' => 'insetti',
                'diet' => 'insettivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['prateria-savana', 'foresta-bosco'],
                'continents' => ['africa', 'europa', 'asia'],
                'abilities' => ['mimetismo', 'velocita'],
            ],
            [
                'name' => 'Lupo grigio',
                'scientific_name' => 'Canis lupus',
                'description' => 'Canide sociale e intelligente, vive in branchi e comunica con ululati, posture e segnali odorosi.',
                'weight_kg' => 45,
                'length_cm' => 160,
                'height_cm' => 85,
                'lifespan_years' => 13,
                'animal_class' => 'mammiferi',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco', 'montagna', 'prateria-savana'],
                'continents' => ['europa', 'asia', 'america-del-nord'],
                'abilities' => ['comunicazione-sonora', 'velocita', 'forza-eccezionale'],
            ],
            [
                'name' => 'Lince euroasiatica',
                'scientific_name' => 'Lynx lynx',
                'description' => 'Felino selvatico delle foreste, riconoscibile dai ciuffi di pelo sulle orecchie.',
                'weight_kg' => 25,
                'length_cm' => 130,
                'height_cm' => 70,
                'lifespan_years' => 17,
                'animal_class' => 'mammiferi',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco', 'montagna'],
                'continents' => ['europa', 'asia'],
                'abilities' => ['visione-notturna', 'salto', 'mimetismo'],
            ],
            [
                'name' => 'Ghepardo',
                'scientific_name' => 'Acinonyx jubatus',
                'description' => 'Felino africano famoso per essere il più veloce animale terrestre sulle brevi distanze.',
                'weight_kg' => 55,
                'length_cm' => 150,
                'height_cm' => 90,
                'lifespan_years' => 12,
                'animal_class' => 'mammiferi',
                'diet' => 'carnivoro',
                'conservation_status' => 'vulnerabile',
                'habitats' => ['prateria-savana'],
                'continents' => ['africa'],
                'abilities' => ['velocita', 'mimetismo'],
            ],
            [
                'name' => 'Albatros urlatore',
                'scientific_name' => 'Diomedea exulans',
                'description' => 'Grande uccello oceanico capace di planare per lunghissime distanze sopra il mare.',
                'weight_kg' => 9,
                'length_cm' => 135,
                'height_cm' => 90,
                'lifespan_years' => 50,
                'animal_class' => 'uccelli',
                'diet' => 'piscivoro',
                'conservation_status' => 'vulnerabile',
                'habitats' => ['mare-oceano'],
                'continents' => ['antartide', 'oceania', 'america-del-sed', 'africa'],
                'abilities' => ['volo', 'termoregolazione-estrema'],
            ],
            [
                'name' => 'Volpe rossa',
                'scientific_name' => 'Vulpes vulpes',
                'description' => 'Canide agile e adattabile, diffuso in molti ambienti e riconoscibile dalla coda folta.',
                'weight_kg' => 8,
                'length_cm' => 110,
                'height_cm' => 40,
                'lifespan_years' => 5,
                'animal_class' => 'mammiferi',
                'diet' => 'onnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco', 'prateria-savana', 'montagna'],
                'continents' => ['europa', 'asia', 'america-del-nord'],
                'abilities' => ['velocita', 'visione-notturna', 'mimetismo'],
            ],
            [
                'name' => 'Pantera nera',
                'scientific_name' => 'Panthera pardus',
                'description' => 'Felino dal mantello scuro, forma melanica di leopardo o giaguaro, agile e furtivo.',
                'weight_kg' => 70,
                'length_cm' => 190,
                'height_cm' => 75,
                'lifespan_years' => 15,
                'animal_class' => 'mammiferi',
                'diet' => 'carnivoro',
                'conservation_status' => 'vulnerabile',
                'habitats' => ['foresta-bosco'],
                'continents' => ['africa', 'asia'],
                'abilities' => ['mimetismo', 'arrampicata', 'visione-notturna'],
            ],
            [
                'name' => 'Puma',
                'scientific_name' => 'Puma concolor',
                'description' => 'Grande felino americano agile e adattabile, capace di vivere in habitat molto diversi.',
                'weight_kg' => 80,
                'length_cm' => 240,
                'height_cm' => 80,
                'lifespan_years' => 13,
                'animal_class' => 'mammiferi',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco', 'montagna', 'prateria-savana'],
                'continents' => ['america-del-nord', 'america-del-sed'],
                'abilities' => ['salto', 'velocita', 'mimetismo'],
            ],
            [
                'name' => 'Pinguino imperatore',
                'scientific_name' => 'Aptenodytes forsteri',
                'description' => 'Il più grande dei pinguini, vive in Antartide ed è adattato al freddo estremo.',
                'weight_kg' => 30,
                'length_cm' => 120,
                'height_cm' => 115,
                'lifespan_years' => 20,
                'animal_class' => 'uccelli',
                'diet' => 'piscivoro',
                'conservation_status' => 'quasi-minacciato',
                'habitats' => ['artico-polare', 'mare-oceano'],
                'continents' => ['antartide'],
                'abilities' => ['nuoto-rapido', 'termoregolazione-estrema', 'comunicazione-sonora'],
            ],
            [
                'name' => 'Zebra di pianura',
                'scientific_name' => 'Equus quagga',
                'description' => 'Erbivoro africano celebre per il mantello a strisce bianche e nere.',
                'weight_kg' => 350,
                'length_cm' => 240,
                'height_cm' => 140,
                'lifespan_years' => 25,
                'animal_class' => 'mammiferi',
                'diet' => 'erbivoro',
                'conservation_status' => 'quasi-minacciato',
                'habitats' => ['prateria-savana'],
                'continents' => ['africa'],
                'abilities' => ['velocita'],
            ],
            [
                'name' => 'Gatto selvatico europeo',
                'scientific_name' => 'Felis silvestris',
                'description' => 'Felino schivo delle foreste europee, antenato del gatto domestico.',
                'weight_kg' => 6,
                'length_cm' => 90,
                'height_cm' => 40,
                'lifespan_years' => 15,
                'animal_class' => 'mammiferi',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco'],
                'continents' => ['europa'],
                'abilities' => ['visione-notturna', 'mimetismo'],
            ],
            [
                'name' => 'Toro',
                'scientific_name' => 'Bos taurus',
                'description' => 'Grande bovino noto per forza fisica e robustezza.',
                'weight_kg' => 900,
                'length_cm' => 250,
                'height_cm' => 170,
                'lifespan_years' => 20,
                'animal_class' => 'mammiferi',
                'diet' => 'erbivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['prateria-savana'],
                'continents' => ['europa', 'asia', 'america-del-nord', 'america-del-sed'],
                'abilities' => ['forza-eccezionale'],
            ],
            [
                'name' => 'Tucano toco',
                'scientific_name' => 'Ramphastos toco',
                'description' => 'Uccello sudamericano dal grande becco colorato, utile per alimentarsi e comunicare.',
                'weight_kg' => 0.6,
                'length_cm' => 60,
                'height_cm' => 35,
                'lifespan_years' => 20,
                'animal_class' => 'uccelli',
                'diet' => 'frugivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco'],
                'continents' => ['america-del-sed'],
                'abilities' => ['volo', 'comunicazione-sonora'],
            ],
            [
                'name' => 'Cavallo',
                'scientific_name' => 'Equus ferus caballus',
                'description' => 'Mammifero erbivoro addomesticato dall’uomo da migliaia di anni.',
                'weight_kg' => 500,
                'length_cm' => 250,
                'height_cm' => 170,
                'lifespan_years' => 30,
                'animal_class' => 'mammiferi',
                'diet' => 'erbivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['prateria-savana'],
                'continents' => ['europa', 'asia', 'america-del-nord', 'america-del-sed'],
                'abilities' => ['velocita'],
            ],
            [
                'name' => 'Topo domestico',
                'scientific_name' => 'Mus musculus',
                'description' => 'Piccolo roditore diffuso in tutto il mondo e molto adattabile.',
                'weight_kg' => 0.03,
                'length_cm' => 20,
                'height_cm' => 5,
                'lifespan_years' => 3,
                'animal_class' => 'mammiferi',
                'diet' => 'onnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco', 'prateria-savana'],
                'continents' => ['africa', 'europa', 'asia', 'america-del-nord', 'america-del-sed', 'oceania'],
                'abilities' => ['arrampicata'],
            ],
            [
                'name' => 'Coyote',
                'scientific_name' => 'Canis latrans',
                'description' => 'Canide nordamericano agile e adattabile, capace di vivere in praterie, deserti e ambienti vicini all’uomo.',
                'weight_kg' => 14,
                'length_cm' => 135,
                'height_cm' => 60,
                'lifespan_years' => 14,
                'animal_class' => 'mammiferi',
                'diet' => 'onnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['prateria-savana', 'deserto', 'foresta-bosco'],
                'continents' => ['america-del-nord'],
                'abilities' => ['velocita', 'comunicazione-sonora'],
            ],
            [
                'name' => 'Coccodrillo del Nilo',
                'scientific_name' => 'Crocodylus niloticus',
                'description' => 'Grande rettile acquatico africano, predatore potente di fiumi, laghi e paludi.',
                'weight_kg' => 500,
                'length_cm' => 500,
                'height_cm' => 60,
                'lifespan_years' => 70,
                'animal_class' => 'rettili',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['fiume-lago', 'palude'],
                'continents' => ['africa'],
                'abilities' => ['forza-eccezionale', 'corazza', 'nuoto-rapido'],
            ],
            [
                'name' => 'Iena maculata',
                'scientific_name' => 'Crocuta crocuta',
                'description' => 'Carnivoro africano sociale e resistente, noto per i richiami simili a risate.',
                'weight_kg' => 70,
                'length_cm' => 160,
                'height_cm' => 85,
                'lifespan_years' => 20,
                'animal_class' => 'mammiferi',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['prateria-savana'],
                'continents' => ['africa'],
                'abilities' => ['forza-eccezionale', 'comunicazione-sonora'],
            ],
            [
                'name' => 'Orso polare',
                'scientific_name' => 'Ursus maritimus',
                'description' => 'Grande predatore artico, specializzato nella vita tra ghiacci marini e acque fredde.',
                'weight_kg' => 500,
                'length_cm' => 280,
                'height_cm' => 160,
                'lifespan_years' => 25,
                'animal_class' => 'mammiferi',
                'diet' => 'carnivoro',
                'conservation_status' => 'vulnerabile',
                'habitats' => ['artico-polare', 'mare-oceano'],
                'continents' => ['america-del-nord', 'europa', 'asia'],
                'abilities' => ['termoregolazione-estrema', 'nuoto-rapido', 'forza-eccezionale'],
            ],
            [
                'name' => 'Rinoceronte nero',
                'scientific_name' => 'Diceros bicornis',
                'description' => 'Grande erbivoro africano dotato di due corni, minacciato soprattutto dal bracconaggio.',
                'weight_kg' => 1200,
                'length_cm' => 375,
                'height_cm' => 160,
                'lifespan_years' => 40,
                'animal_class' => 'mammiferi',
                'diet' => 'erbivoro',
                'conservation_status' => 'gravemente-in-pericolo',
                'habitats' => ['prateria-savana', 'foresta-bosco'],
                'continents' => ['africa'],
                'abilities' => ['forza-eccezionale', 'corazza'],
            ],
            [
                'name' => 'Fenicottero rosa',
                'scientific_name' => 'Phoenicopterus roseus',
                'description' => 'Uccello acquatico dal piumaggio rosato, vive in colonie in zone umide e lagune.',
                'weight_kg' => 3,
                'length_cm' => 145,
                'height_cm' => 140,
                'lifespan_years' => 30,
                'animal_class' => 'uccelli',
                'diet' => 'onnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['palude', 'mare-oceano', 'fiume-lago'],
                'continents' => ['africa', 'europa', 'asia'],
                'abilities' => ['volo', 'termoregolazione-estrema'],
            ],
            [
                'name' => 'Ippopotamo',
                'scientific_name' => 'Hippopotamus amphibius',
                'description' => 'Grande mammifero semiacquatico africano, vive vicino a fiumi e laghi.',
                'weight_kg' => 1500,
                'length_cm' => 400,
                'height_cm' => 150,
                'lifespan_years' => 40,
                'animal_class' => 'mammiferi',
                'diet' => 'erbivoro',
                'conservation_status' => 'vulnerabile',
                'habitats' => ['fiume-lago', 'palude'],
                'continents' => ['africa'],
                'abilities' => ['forza-eccezionale', 'nuoto-rapido'],
            ],
            [
                'name' => 'Giraffa',
                'scientific_name' => 'Giraffa camelopardalis',
                'description' => 'Il più alto animale terrestre, riconoscibile dal collo lungo e dal mantello maculato.',
                'weight_kg' => 1000,
                'length_cm' => 450,
                'height_cm' => 550,
                'lifespan_years' => 25,
                'animal_class' => 'mammiferi',
                'diet' => 'erbivoro',
                'conservation_status' => 'vulnerabile',
                'habitats' => ['prateria-savana', 'foresta-bosco'],
                'continents' => ['africa'],
                'abilities' => ['termoregolazione-estrema'],
            ],
            [
                'name' => 'Scoiattolo rosso',
                'scientific_name' => 'Sciurus vulgaris',
                'description' => 'Piccolo roditore arboricolo europeo, agile tra rami e tronchi.',
                'weight_kg' => 0.35,
                'length_cm' => 40,
                'height_cm' => 20,
                'lifespan_years' => 7,
                'animal_class' => 'mammiferi',
                'diet' => 'onnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco'],
                'continents' => ['europa', 'asia'],
                'abilities' => ['arrampicata', 'salto'],
            ],
            [
                'name' => 'Iguana verde',
                'scientific_name' => 'Iguana iguana',
                'description' => 'Rettile arboricolo tropicale, spesso verde, abile nell’arrampicata e nel nuoto.',
                'weight_kg' => 5,
                'length_cm' => 150,
                'height_cm' => 30,
                'lifespan_years' => 20,
                'animal_class' => 'rettili',
                'diet' => 'erbivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco', 'fiume-lago'],
                'continents' => ['america-del-nord', 'america-del-sed'],
                'abilities' => ['arrampicata', 'nuoto-rapido', 'mimetismo'],
            ],
            [
                'name' => 'Castoro europeo',
                'scientific_name' => 'Castor fiber',
                'description' => 'Roditore semiacquatico capace di costruire dighe e modificare l’ambiente in cui vive.',
                'weight_kg' => 25,
                'length_cm' => 100,
                'height_cm' => 35,
                'lifespan_years' => 12,
                'animal_class' => 'mammiferi',
                'diet' => 'erbivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['fiume-lago', 'foresta-bosco'],
                'continents' => ['europa', 'asia'],
                'abilities' => ['nuoto-rapido', 'forza-eccezionale'],
            ],
            [
                'name' => 'Capibara',
                'scientific_name' => 'Hydrochoerus hydrochaeris',
                'description' => 'Il più grande roditore vivente, vive in gruppo vicino ad ambienti acquatici sudamericani.',
                'weight_kg' => 55,
                'length_cm' => 130,
                'height_cm' => 60,
                'lifespan_years' => 10,
                'animal_class' => 'mammiferi',
                'diet' => 'erbivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['fiume-lago', 'palude', 'prateria-savana'],
                'continents' => ['america-del-sed'],
                'abilities' => ['nuoto-rapido', 'comunicazione-sonora'],
            ],
            [
                'name' => 'Quokka',
                'scientific_name' => 'Setonix brachyurus',
                'description' => 'Piccolo marsupiale australiano, noto per l’espressione del muso simile a un sorriso.',
                'weight_kg' => 4,
                'length_cm' => 55,
                'height_cm' => 30,
                'lifespan_years' => 10,
                'animal_class' => 'mammiferi',
                'diet' => 'erbivoro',
                'conservation_status' => 'vulnerabile',
                'habitats' => ['foresta-bosco'],
                'continents' => ['oceania'],
                'abilities' => ['salto'],
            ],
            [
                'name' => 'Axolotl',
                'scientific_name' => 'Ambystoma mexicanum',
                'description' => 'Anfibio acquatico messicano celebre per la straordinaria capacità di rigenerare parti del corpo.',
                'weight_kg' => 0.08,
                'length_cm' => 25,
                'height_cm' => null,
                'lifespan_years' => 15,
                'animal_class' => 'anfibi',
                'diet' => 'carnivoro',
                'conservation_status' => 'gravemente-in-pericolo',
                'habitats' => ['fiume-lago'],
                'continents' => ['america-del-nord'],
                'abilities' => ['rigenerazione'],
            ],
            [
                'name' => 'Suricato',
                'scientific_name' => 'Suricata suricatta',
                'description' => 'Piccolo mammifero sociale africano, spesso osservato in posizione eretta a fare da sentinella.',
                'weight_kg' => 0.8,
                'length_cm' => 50,
                'height_cm' => 30,
                'lifespan_years' => 12,
                'animal_class' => 'mammiferi',
                'diet' => 'insettivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['deserto', 'prateria-savana'],
                'continents' => ['africa'],
                'abilities' => ['comunicazione-sonora', 'visione-notturna'],
            ],
            [
                'name' => 'Stambecco alpino',
                'scientific_name' => 'Capra ibex',
                'description' => 'Caprino di montagna abile nel muoversi su pareti rocciose e pendii ripidi.',
                'weight_kg' => 90,
                'length_cm' => 150,
                'height_cm' => 100,
                'lifespan_years' => 18,
                'animal_class' => 'mammiferi',
                'diet' => 'erbivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['montagna'],
                'continents' => ['europa'],
                'abilities' => ['arrampicata', 'salto'],
            ],
            [
                'name' => 'Koala',
                'scientific_name' => 'Phascolarctos cinereus',
                'description' => 'Marsupiale australiano arboricolo, specializzato nel nutrirsi di foglie di eucalipto.',
                'weight_kg' => 10,
                'length_cm' => 80,
                'height_cm' => 60,
                'lifespan_years' => 15,
                'animal_class' => 'mammiferi',
                'diet' => 'erbivoro',
                'conservation_status' => 'vulnerabile',
                'habitats' => ['foresta-bosco'],
                'continents' => ['oceania'],
                'abilities' => ['arrampicata'],
            ],
            [
                'name' => 'Corvo imperiale',
                'scientific_name' => 'Corvus corax',
                'description' => 'Uccello molto intelligente, capace di risolvere problemi e comunicare con richiami complessi.',
                'weight_kg' => 1.5,
                'length_cm' => 65,
                'height_cm' => 40,
                'lifespan_years' => 20,
                'animal_class' => 'uccelli',
                'diet' => 'onnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco', 'montagna', 'prateria-savana'],
                'continents' => ['europa', 'asia', 'america-del-nord'],
                'abilities' => ['volo', 'comunicazione-sonora'],
            ],
            [
                'name' => 'Canguro rosso',
                'scientific_name' => 'Osphranter rufus',
                'description' => 'Grande marsupiale australiano, famoso per il potente salto e la lunga coda.',
                'weight_kg' => 85,
                'length_cm' => 240,
                'height_cm' => 180,
                'lifespan_years' => 23,
                'animal_class' => 'mammiferi',
                'diet' => 'erbivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['prateria-savana', 'deserto'],
                'continents' => ['oceania'],
                'abilities' => ['salto', 'velocita'],
            ],
            [
                'name' => 'Tricheco',
                'scientific_name' => 'Odobenus rosmarus',
                'description' => 'Grande mammifero marino artico, riconoscibile dalle lunghe zanne e dai baffi sensibili.',
                'weight_kg' => 1000,
                'length_cm' => 350,
                'height_cm' => null,
                'lifespan_years' => 40,
                'animal_class' => 'mammiferi',
                'diet' => 'carnivoro',
                'conservation_status' => 'vulnerabile',
                'habitats' => ['artico-polare', 'mare-oceano'],
                'continents' => ['america-del-nord', 'europa', 'asia'],
                'abilities' => ['termoregolazione-estrema', 'nuoto-rapido', 'forza-eccezionale'],
            ],
            [
                'name' => 'Pitone reticolato',
                'scientific_name' => 'Malayopython reticulatus',
                'description' => 'Uno dei serpenti più lunghi al mondo, vive nelle foreste tropicali asiatiche.',
                'weight_kg' => 75,
                'length_cm' => 600,
                'height_cm' => null,
                'lifespan_years' => 25,
                'animal_class' => 'rettili',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco', 'palude'],
                'continents' => ['asia'],
                'abilities' => ['mimetismo', 'forza-eccezionale'],
            ],
            [
                'name' => 'Diavolo della Tasmania',
                'scientific_name' => 'Sarcophilus harrisii',
                'description' => 'Marsupiale carnivoro australiano, noto per i vocalizzi intensi e il morso potente.',
                'weight_kg' => 10,
                'length_cm' => 80,
                'height_cm' => 30,
                'lifespan_years' => 6,
                'animal_class' => 'mammiferi',
                'diet' => 'carnivoro',
                'conservation_status' => 'in-pericolo',
                'habitats' => ['foresta-bosco', 'prateria-savana'],
                'continents' => ['oceania'],
                'abilities' => ['forza-eccezionale', 'comunicazione-sonora'],
            ],
            [
                'name' => 'Rana freccia velenosa',
                'scientific_name' => 'Dendrobatidae',
                'description' => 'Piccola rana tropicale dai colori vivaci, famosa per le tossine cutanee di alcune specie.',
                'weight_kg' => 0.005,
                'length_cm' => 5,
                'height_cm' => 2,
                'lifespan_years' => 8,
                'animal_class' => 'anfibi',
                'diet' => 'insettivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco'],
                'continents' => ['america-del-sed'],
                'abilities' => ['veleno', 'salto'],
            ],
            [
                'name' => 'Colibrì gola rubino',
                'scientific_name' => 'Archilochus colubris',
                'description' => 'Piccolo uccello capace di restare fermo in volo grazie al rapidissimo battito delle ali.',
                'weight_kg' => 0.004,
                'length_cm' => 9,
                'height_cm' => 5,
                'lifespan_years' => 5,
                'animal_class' => 'uccelli',
                'diet' => 'nettarivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco'],
                'continents' => ['america-del-nord'],
                'abilities' => ['volo', 'velocita'],
            ],
            [
                'name' => 'Alligatore americano',
                'scientific_name' => 'Alligator mississippiensis',
                'description' => 'Grande rettile semiacquatico delle paludi nordamericane, robusto e ben adattato all’acqua dolce.',
                'weight_kg' => 360,
                'length_cm' => 450,
                'height_cm' => 50,
                'lifespan_years' => 50,
                'animal_class' => 'rettili',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['palude', 'fiume-lago'],
                'continents' => ['america-del-nord'],
                'abilities' => ['forza-eccezionale', 'corazza', 'nuoto-rapido'],
            ],
            [
                'name' => 'Pesce pagliaccio',
                'scientific_name' => 'Amphiprioninae',
                'description' => 'Piccolo pesce tropicale che vive spesso in simbiosi con gli anemoni di mare.',
                'weight_kg' => 0.25,
                'length_cm' => 12,
                'height_cm' => null,
                'lifespan_years' => 10,
                'animal_class' => 'pesci',
                'diet' => 'onnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['mare-oceano'],
                'continents' => ['asia', 'oceania'],
                'abilities' => ['mimetismo', 'nuoto-rapido'],
            ],
            [
                'name' => 'Balenottera azzurra',
                'scientific_name' => 'Balaenoptera musculus',
                'description' => 'Il più grande animale mai vissuto sulla Terra, enorme cetaceo filtratore degli oceani.',
                'weight_kg' => 120000,
                'length_cm' => 3000,
                'height_cm' => null,
                'lifespan_years' => 80,
                'animal_class' => 'mammiferi',
                'diet' => 'carnivoro',
                'conservation_status' => 'in-pericolo',
                'habitats' => ['mare-oceano'],
                'continents' => ['africa', 'europa', 'asia', 'america-del-nord', 'america-del-sed', 'oceania', 'antartide'],
                'abilities' => ['nuoto-rapido', 'comunicazione-sonora', 'termoregolazione-estrema'],
            ],
            [
                'name' => 'Libellula imperatore',
                'scientific_name' => 'Anax imperator',
                'description' => 'Insetto volante rapido e agile, spesso osservato vicino a stagni e corsi d’acqua.',
                'weight_kg' => 0.001,
                'length_cm' => 8,
                'height_cm' => 1,
                'lifespan_years' => 1,
                'animal_class' => 'insetti',
                'diet' => 'insettivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['fiume-lago', 'palude'],
                'continents' => ['africa', 'europa', 'asia'],
                'abilities' => ['volo', 'velocita'],
            ],
            [
                'name' => 'Granchio reale',
                'scientific_name' => 'Paralithodes camtschaticus',
                'description' => 'Grande crostaceo marino dalle lunghe zampe, vive in acque fredde e profonde.',
                'weight_kg' => 10,
                'length_cm' => 180,
                'height_cm' => null,
                'lifespan_years' => 20,
                'animal_class' => 'crostacei',
                'diet' => 'onnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['mare-oceano', 'artico-polare'],
                'continents' => ['asia', 'america-del-nord'],
                'abilities' => ['corazza', 'termoregolazione-estrema'],
            ],
            [
                'name' => 'Rana toro americana',
                'scientific_name' => 'Lithobates catesbeianus',
                'description' => 'Grande rana nordamericana nota per il potente verso e la notevole capacità di salto.',
                'weight_kg' => 0.5,
                'length_cm' => 20,
                'height_cm' => 8,
                'lifespan_years' => 10,
                'animal_class' => 'anfibi',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['fiume-lago', 'palude'],
                'continents' => ['america-del-nord'],
                'abilities' => ['salto', 'comunicazione-sonora'],
            ],
            [
                'name' => 'Pellicano bianco',
                'scientific_name' => 'Pelecanus onocrotalus',
                'description' => 'Grande uccello acquatico caratterizzato dall’ampio sacco golare.',
                'weight_kg' => 12,
                'length_cm' => 180,
                'height_cm' => 150,
                'lifespan_years' => 30,
                'animal_class' => 'uccelli',
                'diet' => 'piscivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['fiume-lago', 'mare-oceano'],
                'continents' => ['africa', 'europa', 'asia'],
                'abilities' => ['volo', 'nuoto-rapido'],
            ],
            [
                'name' => 'Geco tokay',
                'scientific_name' => 'Gekko gecko',
                'description' => 'Rettile notturno dai colori vivaci, abilissimo nell’arrampicarsi su superfici verticali.',
                'weight_kg' => 0.2,
                'length_cm' => 35,
                'height_cm' => 5,
                'lifespan_years' => 10,
                'animal_class' => 'rettili',
                'diet' => 'insettivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco'],
                'continents' => ['asia'],
                'abilities' => ['arrampicata', 'visione-notturna'],
            ],
            [
                'name' => 'Pesce luna',
                'scientific_name' => 'Mola mola',
                'description' => 'Grande pesce oceanico dal corpo appiattito, spesso visibile vicino alla superficie.',
                'weight_kg' => 1000,
                'length_cm' => 300,
                'height_cm' => null,
                'lifespan_years' => 20,
                'animal_class' => 'pesci',
                'diet' => 'carnivoro',
                'conservation_status' => 'vulnerabile',
                'habitats' => ['mare-oceano'],
                'continents' => ['africa', 'europa', 'asia', 'america-del-nord', 'america-del-sed', 'oceania'],
                'abilities' => ['nuoto-rapido'],
            ],
            [
                'name' => 'Calamaro gigante',
                'scientific_name' => 'Architeuthis dux',
                'description' => 'Enorme mollusco abissale, misterioso e raramente osservato vivo nel suo ambiente naturale.',
                'weight_kg' => 275,
                'length_cm' => 1200,
                'height_cm' => null,
                'lifespan_years' => 5,
                'animal_class' => 'molluschi',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['mare-oceano'],
                'continents' => ['africa', 'europa', 'asia', 'america-del-nord', 'america-del-sed', 'oceania'],
                'abilities' => ['mimetismo', 'nuoto-rapido'],
            ],
            [
                'name' => 'Pipistrello vampiro',
                'scientific_name' => 'Desmodus rotundus',
                'description' => 'Piccolo mammifero volante che si nutre di sangue e usa sensi specializzati per orientarsi al buio.',
                'weight_kg' => 0.04,
                'length_cm' => 9,
                'height_cm' => 5,
                'lifespan_years' => 9,
                'animal_class' => 'mammiferi',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['grotte', 'foresta-bosco'],
                'continents' => ['america-del-sed', 'america-del-nord'],
                'abilities' => ['volo', 'ecolocalizzazione', 'visione-notturna'],
            ],
            [
                'name' => 'Formica tagliafoglie',
                'scientific_name' => 'Atta',
                'description' => 'Insetto sociale che taglia foglie per coltivare funghi all’interno del formicaio.',
                'weight_kg' => 0.00001,
                'length_cm' => 2,
                'height_cm' => 1,
                'lifespan_years' => 1,
                'animal_class' => 'insetti',
                'diet' => 'erbivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco'],
                'continents' => ['america-del-nord', 'america-del-sed'],
                'abilities' => ['forza-eccezionale', 'comunicazione-sonora'],
            ],
            [
                'name' => 'Aragosta europea',
                'scientific_name' => 'Homarus gammarus',
                'description' => 'Grande crostaceo marino dotato di robuste chele e corazza resistente.',
                'weight_kg' => 5,
                'length_cm' => 60,
                'height_cm' => null,
                'lifespan_years' => 50,
                'animal_class' => 'crostacei',
                'diet' => 'onnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['mare-oceano'],
                'continents' => ['europa'],
                'abilities' => ['corazza', 'forza-eccezionale'],
            ],
            [
                'name' => 'Vedova nera',
                'scientific_name' => 'Latrodectus mactans',
                'description' => 'Ragno noto per il veleno potente e per il caratteristico segno rosso sull’addome.',
                'weight_kg' => 0.001,
                'length_cm' => 4,
                'height_cm' => null,
                'lifespan_years' => 3,
                'animal_class' => 'aracnidi',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco', 'deserto', 'prateria-savana'],
                'continents' => ['america-del-nord'],
                'abilities' => ['veleno', 'produzione-seta'],
            ],
            [
                'name' => 'Salamandra pezzata',
                'scientific_name' => 'Salamandra salamandra',
                'description' => 'Anfibio europeo dal caratteristico colore nero con macchie gialle.',
                'weight_kg' => 0.04,
                'length_cm' => 25,
                'height_cm' => 4,
                'lifespan_years' => 20,
                'animal_class' => 'anfibi',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco'],
                'continents' => ['europa'],
                'abilities' => ['rigenerazione', 'veleno'],
            ],
            [
                'name' => 'Struzzo',
                'scientific_name' => 'Struthio camelus',
                'description' => 'Il più grande uccello vivente, incapace di volare ma molto veloce nella corsa.',
                'weight_kg' => 120,
                'length_cm' => 250,
                'height_cm' => 270,
                'lifespan_years' => 40,
                'animal_class' => 'uccelli',
                'diet' => 'onnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['prateria-savana'],
                'continents' => ['africa'],
                'abilities' => ['velocita'],
            ],
            [
                'name' => 'Tartaruga gigante delle Galápagos',
                'scientific_name' => 'Chelonoidis niger',
                'description' => 'Una delle tartarughe più grandi del mondo, famosa per la straordinaria longevità.',
                'weight_kg' => 250,
                'length_cm' => 180,
                'height_cm' => 90,
                'lifespan_years' => 120,
                'animal_class' => 'rettili',
                'diet' => 'erbivoro',
                'conservation_status' => 'vulnerabile',
                'habitats' => ['prateria-savana'],
                'continents' => ['america-del-sed'],
                'abilities' => ['corazza'],
            ],
            [
                'name' => 'Cavalluccio marino',
                'scientific_name' => 'Hippocampus',
                'description' => 'Piccolo pesce dalla forma particolare, capace di mimetizzarsi tra alghe e coralli.',
                'weight_kg' => 0.01,
                'length_cm' => 15,
                'height_cm' => null,
                'lifespan_years' => 5,
                'animal_class' => 'pesci',
                'diet' => 'carnivoro',
                'conservation_status' => 'vulnerabile',
                'habitats' => ['mare-oceano'],
                'continents' => ['africa', 'europa', 'asia', 'oceania'],
                'abilities' => ['mimetismo', 'nuoto-rapido'],
            ],
            [
                'name' => 'Lumaca gigante africana',
                'scientific_name' => 'Achatina fulica',
                'description' => 'Grande mollusco terrestre noto per la conchiglia allungata e la crescita rapida.',
                'weight_kg' => 0.3,
                'length_cm' => 20,
                'height_cm' => null,
                'lifespan_years' => 10,
                'animal_class' => 'molluschi',
                'diet' => 'erbivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco'],
                'continents' => ['africa'],
                'abilities' => ['corazza', 'rigenerazione'],
            ],
            [
                'name' => 'Cammello',
                'scientific_name' => 'Camelus bactrianus',
                'description' => 'Mammifero adattato agli ambienti aridi, capace di sopportare lunghi periodi con poca acqua.',
                'weight_kg' => 600,
                'length_cm' => 300,
                'height_cm' => 230,
                'lifespan_years' => 40,
                'animal_class' => 'mammiferi',
                'diet' => 'erbivoro',
                'conservation_status' => 'gravemente-in-pericolo',
                'habitats' => ['deserto', 'prateria-savana'],
                'continents' => ['asia'],
                'abilities' => ['termoregolazione-estrema', 'forza-eccezionale'],
            ],
            [
                'name' => 'Zanzara comune',
                'scientific_name' => 'Culex pipiens',
                'description' => 'Insetto molto diffuso, noto per il caratteristico ronzio e la puntura.',
                'weight_kg' => 0.00001,
                'length_cm' => 1,
                'height_cm' => 1,
                'lifespan_years' => 1,
                'animal_class' => 'insetti',
                'diet' => 'nettarivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['palude', 'fiume-lago'],
                'continents' => ['africa', 'europa', 'asia', 'america-del-nord', 'america-del-sed', 'oceania'],
                'abilities' => ['volo'],
            ],
            [
                'name' => 'Paguro bernardo',
                'scientific_name' => 'Pagurus bernhardus',
                'description' => 'Crostaceo che utilizza conchiglie vuote come protezione del corpo.',
                'weight_kg' => 0.05,
                'length_cm' => 15,
                'height_cm' => null,
                'lifespan_years' => 8,
                'animal_class' => 'crostacei',
                'diet' => 'onnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['mare-oceano'],
                'continents' => ['europa'],
                'abilities' => ['corazza'],
            ],
            [
                'name' => 'Scorpione imperatore',
                'scientific_name' => 'Pandinus imperator',
                'description' => 'Grande scorpione africano dal corpo scuro e dalle robuste chele.',
                'weight_kg' => 0.03,
                'length_cm' => 20,
                'height_cm' => null,
                'lifespan_years' => 8,
                'animal_class' => 'aracnidi',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['foresta-bosco'],
                'continents' => ['africa'],
                'abilities' => ['veleno', 'corazza'],
            ],
            [
                'name' => 'Tritone crestato',
                'scientific_name' => 'Triturus cristatus',
                'description' => 'Anfibio europeo che vive tra ambienti acquatici e terrestri, riconoscibile dalla cresta nel periodo riproduttivo.',
                'weight_kg' => 0.01,
                'length_cm' => 16,
                'height_cm' => 3,
                'lifespan_years' => 12,
                'animal_class' => 'anfibi',
                'diet' => 'carnivoro',
                'conservation_status' => 'non-a-rischio',
                'habitats' => ['fiume-lago', 'palude', 'foresta-bosco'],
                'continents' => ['europa'],
                'abilities' => ['rigenerazione'],
            ]
        ];

        foreach ($animals as $data) {
            $animalClass = $animalClasses->where('slug', $data['animal_class'])->first();
            $diet = $diets->where('slug', $data['diet'])->first();
            $conservationStatus = $conservationStatuses->where('slug', $data['conservation_status'])->first();

            $slug = generateUniqueSlug(Animal::class, $data['name']);

            $imageFile = $slug . '.png';

            $cardSourcePath = database_path('seeders/assets/animals/card_image/' . $imageFile);
            $realSourcePath = database_path('seeders/assets/animals/real_image/' . $imageFile);

            $cardStoragePath = 'animals/card_image/' . $imageFile;
            $realStoragePath = 'animals/real_image/' . $imageFile;

            if (File::exists($cardSourcePath)) {
                Storage::disk('public')->put($cardStoragePath, File::get($cardSourcePath));
            }

            if (File::exists($realSourcePath)) {
                Storage::disk('public')->put($realStoragePath, File::get($realSourcePath));
            }

            $animal = new Animal();

            $animal->name = ucfirst($data['name']);
            $animal->slug = $slug;
            $animal->scientific_name = $data['scientific_name'];
            $animal->card_image = $cardStoragePath;
            $animal->real_image = $realStoragePath;
            $animal->description = ucfirst($data['description']);
            $animal->weight_kg = $data['weight_kg'];
            $animal->length_cm = $data['length_cm'];
            $animal->height_cm = $data['height_cm'];
            $animal->lifespan_years = $data['lifespan_years'];

            $animal->animal_class_id = $animalClass->id;
            $animal->diet_id = $diet->id;
            $animal->conservation_status_id = $conservationStatus->id;

            $animal->save();

            foreach ($data['habitats'] as $habitatSlug) {
                $habitat = $habitats->where('slug', $habitatSlug)->first();

                if ($habitat) {
                    $animal->habitats()->attach($habitat->id);
                }
            }

            foreach ($data['continents'] as $continentSlug) {
                $continent = $continents->where('slug', $continentSlug)->first();

                if ($continent) {
                    $animal->continents()->attach($continent->id);
                }
            }

            foreach ($data['abilities'] as $abilitySlug) {
                $ability = $abilities->where('slug', $abilitySlug)->first();

                if ($ability) {
                    $animal->abilities()->attach($ability->id);
                }
            }
        }
    }
}
